import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { Word } from "../../src/content/word.ts";
import {
  aksaraEngineRulesetId,
  murdaLinks,
  nglegena,
  padaCatalogue,
  rekan,
  sandhangan,
  swara,
  swaraCatalogue,
  swaraLongForms,
} from "../../src/engine/index.ts";

// Derives the exact code-point set the UI needs from its string sources and
// writes fonts/glyphset.txt, the input of tools/fonts/subset.sh.
// Usage: node tools/fonts/glyphset.ts

const root = join(fileURLToPath(import.meta.url), "..", "..", "..");
const header = "# generated by tools/fonts/glyphset.ts — do not edit";

/** Code points that never go into the MPLUS subsets. */
export function isExcluded(cp: number): boolean {
  return (
    cp <= 0x1f ||
    (cp >= 0x7f && cp <= 0x9f) ||
    (cp >= 0xa980 && cp <= 0xa9df) || // Jejeg serves the Javanese block
    cp === 0x200c ||
    cp === 0x200d ||
    cp === 0x25cc ||
    cp === 0xfe0f ||
    /\p{Extended_Pictographic}/u.test(String.fromCodePoint(cp)) // system emoji
  );
}

function readJson(...path: string[]): unknown {
  return JSON.parse(readFileSync(join(root, ...path), "utf8"));
}

function addText(out: Set<number>, text: string): void {
  for (const ch of text) out.add(ch.codePointAt(0)!);
}

function addStrings(out: Set<number>, value: unknown): void {
  if (typeof value === "string") addText(out, value);
  else if (Array.isArray(value)) value.forEach((v) => addStrings(out, v));
  else if (value !== null && typeof value === "object") {
    Object.values(value).forEach((v) => addStrings(out, v));
  }
}

/**
 * Error messages quote the offending input back ('Unknown character "٣"').
 * The echo is arbitrary user input, not UI text, and falls back to the system
 * font; only the fixed message wording is derived.
 */
const echoedInput = /^(Unknown character ")[^]*(")$/u;

type FixtureEntry = [string, ...unknown[]];

interface Fixture {
  toLatin: [string, string, FixtureEntry][];
  toAksara: [string, boolean, FixtureEntry][];
}

/** Every Latin string or displayed message the Dart-parity fixture records. */
function addFixtureText(out: Set<number>): void {
  const fixture = readJson(
    "tests",
    "engine",
    "fixtures",
    "dart-ebc7cb5.json",
  ) as Fixture;
  for (const [, , result] of [...fixture.toLatin, ...fixture.toAksara]) {
    const [status, a, b] = result as [string, unknown, unknown];
    if (status === "s" && typeof a === "string") addText(out, a);
    else if (status === "a" && typeof a === "string") addText(out, a);
    else if (status === "e" && typeof b === "string") {
      addText(out, b.replace(echoedInput, "$1$2"));
    }
  }
}

/** The sorted, deduplicated, non-excluded code points the UI needs. */
export function computeGlyphSet(): number[] {
  const out = new Set<number>();
  for (let cp = 0x20; cp <= 0x7e; cp++) out.add(cp);
  for (let cp = 0xa0; cp <= 0xff; cp++) out.add(cp);

  addStrings(out, readJson("src", "l10n", "id.json"));
  addStrings(out, readJson("src", "l10n", "en.json"));

  const contentDir = join(root, "public", "content", "v1");
  for (const file of readdirSync(contentDir).filter((f) => f.endsWith(".json"))) {
    addStrings(out, readJson("public", "content", "v1", file));
  }
  const words = readJson("public", "content", "v1", "words.json") as {
    words: Record<string, unknown>[];
  };
  for (const raw of words.words) addText(out, Word.fromJson(raw).display);

  const catalog = [
    ...nglegena,
    ...murdaLinks.map((l) => l.aksara),
    ...swara,
    ...swaraCatalogue,
    ...rekan,
    ...sandhangan,
  ];
  for (const e of catalog) {
    addText(out, e.latinPujl);
    addText(out, e.latinJgst);
  }
  for (const form of swaraLongForms.values()) {
    addText(out, form.latinPujl);
    addText(out, form.latinJgst);
  }
  for (const p of padaCatalogue) if (p.latin !== null) addText(out, p.latin);

  addFixtureText(out);
  addText(out, aksaraEngineRulesetId);

  return [...out].filter((cp) => !isExcluded(cp)).sort((a, b) => a - b);
}

/** Text of fonts/glyphset.txt for the given code points. */
export function renderGlyphSet(codepoints: readonly number[]): string {
  const lines = codepoints.map(
    (cp) => `U+${cp.toString(16).toUpperCase().padStart(4, "0")}`,
  );
  return `${header}\n${lines.join("\n")}\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const set = computeGlyphSet();
  writeFileSync(join(root, "fonts", "glyphset.txt"), renderGlyphSet(set));
  console.log(`glyphset: ${set.length} code points`);
}
