import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/**
 * Generates src/engine/codepoints.ts from the archived UnicodeData slice at
 * docs/references/unicode-javanese-block.txt. Run from the repository root:
 *   npm run gen:codepoints
 */
export function renderCodepointsModule(sliceText: string): string {
  const entries: string[] = [];
  for (const line of sliceText.split(/\r?\n/)) {
    const parts = line.split(";");
    if (parts.length < 2) continue;
    entries.push(`  '${parts[1]}': 0x${parts[0]!.toLowerCase()},`);
  }
  return [
    "// GENERATED CODE — do not edit by hand.",
    "// Generated by tools/gen-codepoints.ts from",
    "// docs/references/unicode-javanese-block.txt (Unicode Character",
    "// Database, Javanese block U+A980..U+A9DF). Regenerate:",
    "//   npm run gen:codepoints",
    "",
    "/**",
    " * Codepoints of all assigned characters in the Javanese Unicode",
    " * block, keyed by official Unicode character name.",
    " */",
    "export const javaneseCodepoints: Readonly<Record<string, number>> = {",
    ...entries,
    "};",
    "",
    "/**",
    " * Returns the single-character string for an official Unicode name.",
    " * Throws for unknown names so bad data fails fast.",
    " */",
    "export function javaneseChar(unicodeName: string): string {",
    "  const cp = Object.hasOwn(javaneseCodepoints, unicodeName)",
    "    ? javaneseCodepoints[unicodeName]",
    "    : undefined;",
    "  if (cp === undefined) {",
    '    throw new Error(`Unknown Javanese Unicode name: "${unicodeName}"`);',
    "  }",
    "  return String.fromCodePoint(cp);",
    "}",
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const slice = readFileSync(
    "docs/references/unicode-javanese-block.txt",
    "utf8",
  );
  writeFileSync("src/engine/codepoints.ts", renderCodepointsModule(slice));
  console.log(
    `Wrote src/engine/codepoints.ts (${slice.split(/\r?\n/).filter((l) => l.split(";").length >= 2).length} characters).`,
  );
}
